### ISSUE TITLE
Unable to find codes/RealDAN folder

### ISSUE THREAD

**Issue by zdyshine** [greatlog/RealDAN#1]
This idea looks great, thanks to open source!  But I can't find codes/RealDAN folder, haven't I provided it yet？
？

**Comment by greatlog** [comment]
Sorry, there were some mistakes in the readme file. It should work now. If there are any other problems. please let me know. Thanks.

**Comment by zdyshine** [comment]
> Sorry, there were some mistakes in the readme file. It should work now. If there are any other problems. please let me know. Thanks.
get it~
