### ISSUE TITLE
question about the setting1 on experiment

### ISSUE THREAD

**Issue by Laser-one** [greatlog/RealDAN#3]
In the experiment of Setting1, the output of the Estimator is degradation code or PCA code like previous paper? Thanks for your amazing work and code.

**Comment by greatlog** [comment]
It is the degradation code, which consists of the parameters of the blur kernel In setting 1.

**Comment by Laser-one** [comment]
Thank you, the response was too fast. Is this the power of the Chinese Academy of Sciences' PHD?
