### ISSUE TITLE
无法训练得到论文中的结果

### ISSUE THREAD

**Issue by Arcananana** [greatlog/RealDAN#4]
作者您好，我尝试重训DAN在real-world合成数据集上4x超分的结果，但是我发现训练很快收敛，并且在验证集上的psnr逐渐降低。
前100000次迭代的验证结果如下：
23-09-26 01:19:10.436 - INFO:  <epoch: 94, iter:   5,000, Average sccores:	psnr: 22.921618; ssim: 0.604642; 
23-09-26 02:05:25.968 - INFO:  <epoch:188, iter:  10,000, Average sccores:	psnr: 23.417599; ssim: 0.623735; 
23-09-26 02:51:48.937 - INFO:  <epoch:283, iter:  15,000, Average sccores:	psnr: 23.514685; ssim: 0.629169; 
23-09-26 03:37:47.865 - INFO:  <epoch:377, iter:  20,000, Average sccores:	psnr: 23.547827; ssim: 0.631476; 
23-09-26 04:22:14.282 - INFO:  <epoch:471, iter:  25,000, Average sccores:	psnr: 23.571558; ssim: 0.631415; 
23-09-26 05:07:12.161 - INFO:  <epoch:566, iter:  30,000, Average sccores:	psnr: 23.587416; ssim: 0.631748; 
23-09-26 05:53:09.046 - INFO:  <epoch:660, iter:  35,000, Average sccores:	psnr: 23.586239; ssim: 0.631668; 
23-09-26 06:38:48.869 - INFO:  <epoch:754, iter:  40,000, Average sccores:	psnr: 23.589043; ssim: 0.632581; 
23-09-26 07:25:00.470 - INFO:  <epoch:849, iter:  45,000, Average sccores:	psnr: 23.580803; ssim: 0.632208; 
23-09-26 08:11:06.986 - INFO:  <epoch:943, iter:  50,000, Average sccores:	psnr: 23.565691; ssim: 0.632091; 
23-09-26 08:57:02.359 - INFO:  <epoch:1037, iter:  55,000, Average sccores:	psnr: 23.557306; ssim: 0.631869; 
23-09-26 09:43:12.951 - INFO:  <epoch:1132, iter:  60,000, Average sccores:	psnr: 23.540745; ssim: 0.631238; 
23-09-26 10:29:18.248 - INFO:  <epoch:1226, iter:  65,000, Average sccores:	psnr: 23.531569; ssim: 0.630892; 
23-09-26 11:15:16.303 - INFO:  <epoch:1320, iter:  70,000, Average sccores:	psnr: 23.525421; ssim: 0.630781; 
23-09-26 12:01:29.084 - INFO:  <epoch:1415, iter:  75,000, Average sccores:	psnr: 23.514370; ssim: 0.630370; 
23-09-26 12:47:46.191 - INFO:  <epoch:1509, iter:  80,000, Average sccores:	psnr: 23.503069; ssim: 0.630095; 
23-09-26 13:33:51.775 - INFO:  <epoch:1603, iter:  85,000, Average sccores:	psnr: 23.487091; ssim: 0.629482; 
23-09-26 14:20:05.914 - INFO:  <epoch:1698, iter:  90,000, Average sccores:	psnr: 23.481306; ssim: 0.629495; 
23-09-26 15:06:08.774 - INFO:  <epoch:1792, iter:  95,000, Average sccores:	psnr: 23.476807; ssim: 0.629153; 
23-09-26 15:51:55.213 - INFO:  <epoch:1886, iter: 100,000, Average sccores:	psnr: 23.469683; ssim: 0.629166; 

而您提供的预训练模型测得的psnr值为23.82,请问有什么我遗漏的地方吗？我的配置文件使用的是RealDAN/codes/config/RealDAN/options/train/dan_edsr_ema.yml，仅修改了文件路径。

**Comment by greatlog** [comment]
在DDP训练的时候有个bug忘记改了，已经提交新的commit https://github.com/greatlog/RealDAN/commit/d447dfa89c64378dcc007098a5e44e79f9d268ae
现在应该没问题了。

在yml设置里，datasets/train 字段里有一个 ratio
https://github.com/greatlog/RealDAN/blob/d447dfa89c64378dcc007098a5e44e79f9d268ae/codes/config/RealDAN/options/train/dan_edsr_ema.yml#L24
设置为一个比较大的数（示例是256）也能解决这个问题。

**Comment by Arcananana** [comment]
谢谢您的解答，验证发现是ratio的问题，感谢！
